#!/usr/bin/python3

from PIL import Image, ImageEnhance
import glob, os, argparse

parser = argparse.ArgumentParser(description='Doot Doot')
parser.add_argument('filename', nargs=1, help='Image file to process.')
parser.add_argument('rescale', nargs=1, type=int, help='Rescaling size.')

charmap = "@MBHENR#KWXDFPQASUZbdehx*8Gm&04LOVYkpq5Tagns69owz$CIu23Jcfry%1v7l+it[] {}?j|()=~!-/<>\\\"^_';,:`. "

def main():
    args = parser.parse_args()

    im = Image.open(args.filename[0])
    enhancer = ImageEnhance.Contrast(im)

    im = enhancer.enhance(1.3)

    picsize = im.size

    resize = (int(picsize[0]/args.rescale[0]), int(picsize[1]/(args.rescale[0]*2 - 1)))
    convert(resize, im)

def convert(size, image):
    inner = image.resize(size) 
    pixels = inner.load()
    for i in range(size[1]):
        for j in range(size[0]):
            print(charmap[pixelbright(pixels[j,i])], end = '')
        print()


def calcbright(pixels, size):
    total = 0
    for i in range(size):
        for j in range(size):
            total += pixelbright(pixels[i,j])
    return total        

def pixelbright(pixel):
    return int((pixel[0] + pixel[1] + pixel[2])/765 * 95)
     

if __name__ == "__main__":
    main()
